server:
  port: 8020
spring:
  application:
    name: consumer-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: consumer-user-8020  #多个服务id必须不同
    prefer-ip-address: true
feign:
   hystrix:
     enabled: true                    #启动熔断器机制 !!!!!!!!!!!!!      